name: Task
description: Create a new task (documentation, maintenance, etc.)
title: "[Task]: "
labels: ["task"]
body:
  - type: markdown
    attributes:
      value: |
        Use this template to create a new task for documentation, maintenance, or other project work.
  - type: dropdown
    id: type
    attributes:
      label: Task Type
      description: What type of task is this?
      options:
        - Documentation
        - Maintenance
        - Testing
        - CI/CD
        - Refactoring
        - Other
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Task Description
      description: Describe what needs to be done
      placeholder: "A clear and concise description of the task..."
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: What needs to be completed for this task to be considered done?
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Criteria 3
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this task?
      options:
        - High
        - Medium
        - Low
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any additional context or resources needed for this task 